export SNOWFLAKE_ACCOUNT := tk83970.ap-northeast-1.aws
export SNOWFLAKE_USER := CI_DBT_PLAYGROUND_TERRAFORM
export SNOWFLAKE_PRIVATE_KEY
export SNOWFLAKE_PRIVATE_KEY_PASSPHRASE
export SNOWFLAKE_AUTHENTICATOR := JWT

terraform_command := terraform
